# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Android
android.useAndroidX=true
android.nonTransitiveRClass=false

# JDK Image
android.disableJdkImageTransform=true

# compileSdk
android.suppressUnsupportedCompileSdk=34

# Kotlin
kotlin.code.style=official

# Enable Gradle build cache
org.gradle.caching=true

# Enable configuration cache (disabled for now due to fat-aar plugin)
# org.gradle.configuration-cache=true